server:
  port: 19483
  servlet:
    context-path: /jw
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 3000ms
  servlet:
    multipart:
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml   # Mapper XML文件路径
  type-aliases-package: com.shq.demo.entity  # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true  # 驼峰命名映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志（开发环境）