server:
  port: 19485
  servlet:
    context-path: /jw
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
spring:
  config:
    import:
      - classpath:dao-config.yaml
  redis:
    host: localhost
    port: 6379
    timeout: 3000ms
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 缓存过期时间10分钟（毫秒）
      cache-null-values: false  # 是否缓存空值
      use-key-prefix: true  # 使用key前缀
  servlet:
    multipart:
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB

management:
  endpoints:
    web:
      exposure:
        include: env,configprops